name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install Docusaurus dependencies
        run: npm ci
        working-directory: docs/docusaurus

      - name: Run pre-checks (audit, lint, format)
        working-directory: docs/docusaurus
        run: |
          npm audit || echo "Audit check failed"
          npm run lint || echo "Lint check failed"
          npm run format:check || echo "Format check failed"

      - name: Build Docusaurus site
        working-directory: docs/docusaurus
        run: npm run docs:build

      - name: Generate PDF
        working-directory: docs/docusaurus
        run: npm run docs:pdf

      - name: Move PDF to static directory
        run: |
          mkdir -p docs/docusaurus/static
          mv docs/user-guide.pdf docs/docusaurus/static/user-guide.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/docusaurus/build
