name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Validate framework
      run: |
        test -f package.json && echo "✅ Package.json exists"
        test -d src && echo "✅ Source directory exists"
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run API tests
      run: |
        if [ -z "$SF_USERNAME" ] || [ -z "$SF_PASSWORD" ] || [ -z "$SF_INSTANCE_URL" ]; then
          echo "⚠️ Skipping API tests - Salesforce credentials not configured"
          exit 0
        fi
        npx playwright test src/tests/api
      env:
        CI: true
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        SF_API_VERSION: ${{ secrets.SF_API_VERSION }}
        TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
        TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
        TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
        TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ci-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7