name: Salesforce Tests Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  salesforce-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright
      run: npx playwright install chromium
    
    - name: Run Salesforce tests only
      run: npm run test:salesforce
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
        SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
        SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
        SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
        HEADLESS: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: salesforce-test-results
        path: |
          test-results/
          playwright-report/
          auth/
        retention-days: 7