name: TestRail Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-testrail:
    name: API TestRail Integration
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run API TestRail integration
      run: npm run test:testrail-demo
      env:
        CI: true
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
        TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
        TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
        TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
        TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
    
    - name: Upload API test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-testrail-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7

  ui-testrail:
    name: UI TestRail Integration
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run UI TestRail integration
      run: npm run test:ui-testrail-final
      env:
        CI: true
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
        TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
        TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
        TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        TESTRAIL_PROJECT_ID: ${{ secrets.TESTRAIL_PROJECT_ID }}
        TESTRAIL_SUITE_ID: ${{ secrets.TESTRAIL_SUITE_ID }}
    
    - name: Upload UI test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ui-testrail-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7